- name: ceate IBM Cloud infra - Security groups for ALB and VSI instances, 2 VSI instances, Target Group and ALB.
  hosts: localhost
  collections:
   - ibm.cloudcollection
  vars:
    name_prefix: ansible-test
    vsi_image: ibm-debian-11-2-minimal-amd64-1
    vsi_profile: bx2-2x8
    ssh_public_key: demo-ssh
    vpc_name: "{{ name_prefix }}-vpc"
    subnet_name: "{{ name_prefix }}-subnet"
    total_ipv4_address_count: 256
    zone: us-south-3
    ssh_key_name: "{{ name_prefix }}-ssh-key"
    vsi_name: "{{ name_prefix }}-vsi"
    fip_name: "{{ name_prefix }}-fip"
    
    sg_4_alb: demo-alb-sg
    sg_4_ec2: demo-ec2-sg
    
    tg_name: demo-appsvr-tg   
    alb_name: demo-appsvr-alb

  tasks:
    # - name: Create IBM Cloud VSI instance
